name: totems
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - matplotlib
  - scipy
  - imageio
  - scikit-learn
  - llvm
  - pip:
    - mitsuba
    - tensorboard
    - torchaudio
    - psutil
    - PyWavelets
    - opencv-python
